import { buildWorkflowTemplate } from "./buildWorkflowTemplate";
import type { WorkflowTemplate } from "../types";

const CIVIL = "civil-engineering";
const CIVIL_NAME = "Civil Engineering";

type CivilWorkflowInput = Omit<
  import("./buildWorkflowTemplate").WorkflowDefinitionInput,
  "disciplineId" | "disciplineName"
>;

const civilWorkflowInputs: CivilWorkflowInput[] = [
  {
    id: "highway-dpr-workflow",
    title: "Highway DPR Workflow",
    overview:
      "End-to-end workflow for preparing a Detailed Project Report for highway schemes.",
    objective:
      "Produce a DPR-ready package with design justification, quantities, cost estimates, and compliance documentation.",
    prerequisites: [
      "Approved alignment and survey data",
      "Traffic projections",
      "Geotechnical investigation report",
    ],
    activityTitles: [
      { title: "Define project scope and corridor", aiAssistance: ["next-step", "create-report"] },
      { title: "Review applicable IRC and MoRTH standards", aiAssistance: ["suggest-standard"] },
      { title: "Complete geometric and pavement design", aiAssistance: ["generate-checklist", "create-report"] },
      { title: "Prepare quantities and cost estimate", aiAssistance: ["prepare-boq", "create-report"] },
      { title: "Compile DPR chapters and annexures", aiAssistance: ["generate-document", "review-step"] },
      { title: "Quality review and submission checklist", aiAssistance: ["generate-checklist", "review-step"] },
    ],
    requiredDocuments: ["Survey data", "Traffic study", "Geotechnical report", "DPR template"],
    requiredStandards: ["IRC:37", "IRC:73", "IRC:86", "MoRTH Specifications"],
    requiredCalculations: ["Pavement design", "Earthwork volumes", "Sight distance"],
    professionalTools: ["DPR template", "BOQ tool", "Rate analysis"],
    outputs: ["DPR document", "Design drawings list", "Cost estimate", "BOQ"],
    qualityChecks: ["Standards compliance", "Design review", "Quantity verification"],
    completionChecklist: [
      "All DPR chapters complete",
      "Calculations attached",
      "BOQ verified",
      "Peer review done",
      "Submission package ready",
    ],
  },
  {
    id: "pavement-design-workflow",
    title: "Pavement Design Workflow",
    overview: "Flexible and rigid pavement design from traffic and subgrade inputs.",
    objective: "Deliver pavement layer design with IRC-compliant thickness and material specifications.",
    prerequisites: ["CBR/subgrade data", "Traffic loading (MSA)", "Design life"],
    activityTitles: [
      { title: "Collect traffic and subgrade inputs" },
      { title: "Select pavement type and standards", aiAssistance: ["suggest-standard"] },
      { title: "Run pavement thickness calculations", aiAssistance: ["next-step", "create-report"] },
      { title: "Define layer materials and specifications" },
      { title: "Prepare design report and drawings list", aiAssistance: ["generate-document", "review-step"] },
    ],
    requiredDocuments: ["Traffic data sheet", "Soil investigation report"],
    requiredStandards: ["IRC:37", "IRC:58", "IS:2386"],
    requiredCalculations: ["Flexible pavement design", "Rigid pavement design"],
    professionalTools: ["Pavement calculator", "Design report template"],
    outputs: ["Pavement design report", "Layer schedule", "Material specifications"],
    qualityChecks: ["Traffic class verified", "CBR validated", "Thickness checked"],
    completionChecklist: ["Inputs verified", "Calculations complete", "Report approved"],
  },
  {
    id: "bridge-design-workflow",
    title: "Bridge Design Workflow",
    overview: "Structural bridge design from concept to detailed design package.",
    objective: "Produce IRC-compliant bridge design with load analysis and drawings schedule.",
    prerequisites: ["Hydraulic data", "Site survey", "Soil bearing capacity"],
    activityTitles: [
      { title: "Define bridge span and loading criteria" },
      { title: "Apply IRC bridge codes", aiAssistance: ["suggest-standard"] },
      { title: "Perform structural analysis", aiAssistance: ["create-report"] },
      { title: "Design superstructure and substructure" },
      { title: "Prepare BOQ and design report", aiAssistance: ["prepare-boq", "generate-document"] },
    ],
    requiredDocuments: ["Hydrological study", "Geotechnical report", "Design basis"],
    requiredStandards: ["IRC:6", "IRC:21", "IRC:112"],
    requiredCalculations: ["Load analysis", "Foundation design", "Reinforcement design"],
    professionalTools: ["Structural calculator", "BOQ tool"],
    outputs: ["Bridge design report", "BOQ", "Drawing schedule"],
    qualityChecks: ["Load combinations checked", "Foundation capacity verified"],
    completionChecklist: ["Analysis complete", "Drawings listed", "BOQ prepared"],
  },
  {
    id: "building-design-workflow",
    title: "Building Design Workflow",
    overview: "Multi-storey building structural and compliance design workflow.",
    objective: "Deliver building design package per IS codes and local bylaws.",
    prerequisites: ["Architectural drawings", "Soil report", "Seismic zone data"],
    activityTitles: [
      { title: "Review architectural layout and loads" },
      { title: "Apply IS structural codes", aiAssistance: ["suggest-standard"] },
      { title: "Structural modelling and analysis" },
      { title: "Design foundations, columns, and slabs" },
      { title: "Prepare calculation report and BOQ", aiAssistance: ["prepare-boq", "create-report"] },
    ],
    requiredDocuments: ["Architectural GA drawings", "Soil investigation"],
    requiredStandards: ["IS:456", "IS:1893", "IS:875", "NBC"],
    requiredCalculations: ["Load analysis", "RCC design", "Foundation design"],
    professionalTools: ["Structural design tool", "BOQ estimator"],
    outputs: ["Structural design report", "Calculation sheets", "BOQ"],
    qualityChecks: ["Seismic compliance", "Deflection checks", "Reinforcement detailing"],
    completionChecklist: ["Analysis approved", "Calculations signed off", "BOQ verified"],
  },
  {
    id: "tender-preparation-workflow",
    title: "Tender Preparation Workflow",
    overview: "Prepare tender documents, schedules, and technical specifications.",
    objective: "Produce a complete tender package ready for publication.",
    prerequisites: ["Approved DPR/scope", "Schedule of rates", "Draft contract conditions"],
    activityTitles: [
      { title: "Define tender scope and eligibility" },
      { title: "Prepare technical specifications", aiAssistance: ["suggest-standard", "generate-document"] },
      { title: "Compile BOQ and rate schedule", aiAssistance: ["prepare-boq"] },
      { title: "Draft tender conditions and forms" },
      { title: "Tender review and approval", aiAssistance: ["generate-checklist", "review-step"] },
    ],
    requiredDocuments: ["Scope document", "Draft contract", "BOQ"],
    requiredStandards: ["MoRTH/CPWD specs", "Applicable IS codes"],
    requiredCalculations: ["Cost estimate", "Rate analysis"],
    professionalTools: ["Tender template", "BOQ tool"],
    outputs: ["Tender document", "Technical specs", "BOQ", "Bid forms"],
    qualityChecks: ["Spec completeness", "BOQ accuracy", "Legal review"],
    completionChecklist: ["Tender approved", "BOQ verified", "Publication ready"],
  },
  {
    id: "boq-preparation-workflow",
    title: "BOQ Preparation Workflow",
    overview: "Bill of quantities preparation with measurement and rate analysis.",
    objective: "Deliver accurate BOQ aligned with drawings and specifications.",
    prerequisites: ["Approved drawings", "Specifications", "Measurement rules"],
    activityTitles: [
      { title: "Review scope and measurement conventions" },
      { title: "Take off quantities from drawings" },
      { title: "Apply specifications and rates", aiAssistance: ["prepare-boq", "suggest-standard"] },
      { title: "Prepare rate analysis", aiAssistance: ["create-report"] },
      { title: "BOQ review and finalization", aiAssistance: ["review-step", "generate-checklist"] },
    ],
    requiredDocuments: ["Drawings", "Specifications", "SOR reference"],
    requiredStandards: ["MoRTH/CPWD SOR", "IS measurement standards"],
    requiredCalculations: ["Quantity take-off", "Rate analysis"],
    professionalTools: ["BOQ tool", "Rate analysis template"],
    outputs: ["BOQ schedule", "Rate analysis sheets"],
    qualityChecks: ["Quantity cross-check", "Unit consistency", "Rate validation"],
    completionChecklist: ["BOQ complete", "Rates verified", "Review signed"],
  },
  {
    id: "quantity-estimation-workflow",
    title: "Quantity Estimation Workflow",
    overview: "Engineering quantity estimation for planning and costing.",
    objective: "Produce verified quantity estimates for project planning.",
    prerequisites: ["Design drawings", "Work breakdown structure"],
    activityTitles: [
      { title: "Define estimation scope" },
      { title: "Extract quantities by work item" },
      { title: "Validate against design assumptions", aiAssistance: ["review-step"] },
      { title: "Prepare estimation summary", aiAssistance: ["create-report", "prepare-boq"] },
    ],
    requiredDocuments: ["Drawings", "WBS", "Design basis"],
    requiredStandards: ["Measurement standards"],
    requiredCalculations: ["Earthwork", "Concrete", "Steel quantities"],
    professionalTools: ["Estimation tool", "Spreadsheet template"],
    outputs: ["Quantity estimate report", "Summary tables"],
    qualityChecks: ["Cross-check with drawings", "Unit verification"],
    completionChecklist: ["Estimates complete", "Review done"],
  },
  {
    id: "site-execution-workflow",
    title: "Site Execution Workflow",
    overview: "Site execution planning, monitoring, and documentation.",
    objective: "Guide field execution with method statements and site records.",
    prerequisites: ["Approved drawings", "Method statements", "Site mobilization plan"],
    activityTitles: [
      { title: "Mobilize site and review method statement", aiAssistance: ["generate-document"] },
      { title: "Set out works and commence execution" },
      { title: "Daily progress and site records", aiAssistance: ["create-report", "generate-inspection"] },
      { title: "Coordinate inspections and tests" },
      { title: "Close out site activities", aiAssistance: ["review-step", "generate-checklist"] },
    ],
    requiredDocuments: ["Method statement", "Drawings", "Site diary template"],
    requiredStandards: ["Project specifications", "Safety standards"],
    requiredCalculations: ["Progress quantities"],
    professionalTools: ["Site diary", "Inspection format"],
    outputs: ["Daily reports", "Site instructions", "Progress records"],
    qualityChecks: ["Workmanship", "Safety compliance", "Test results"],
    completionChecklist: ["Works complete", "Records filed", "Snag list closed"],
  },
  {
    id: "qa-qc-workflow",
    title: "QA/QC Workflow",
    overview: "Quality assurance and quality control for civil works.",
    objective: "Ensure works meet specifications through systematic QA/QC.",
    prerequisites: ["QA plan", "ITP", "Test schedules"],
    activityTitles: [
      { title: "Review QA plan and ITP", aiAssistance: ["suggest-standard"] },
      { title: "Conduct material and work inspections", aiAssistance: ["generate-inspection", "generate-checklist"] },
      { title: "Record test results", aiAssistance: ["create-report"] },
      { title: "Manage non-conformances" },
      { title: "QA/QC close-out", aiAssistance: ["review-step", "generate-checklist"] },
    ],
    requiredDocuments: ["QA plan", "ITP", "Test reports"],
    requiredStandards: ["IS codes", "Project specifications"],
    requiredCalculations: ["Test result evaluation"],
    professionalTools: ["Inspection checklist", "NCR form"],
    outputs: ["Inspection reports", "Test certificates", "QA close-out report"],
    qualityChecks: ["ITP adherence", "Test compliance", "NCR closure"],
    completionChecklist: ["All tests passed", "NCRs closed", "QA report approved"],
  },
  {
    id: "project-completion-workflow",
    title: "Project Completion Workflow",
    overview: "Project handover, completion documentation, and defect liability.",
    objective: "Complete project closure with as-built records and handover package.",
    prerequisites: ["Substantial completion achieved", "Test certificates", "As-built drawings"],
    activityTitles: [
      { title: "Compile completion documentation" },
      { title: "Conduct final inspections", aiAssistance: ["generate-inspection", "generate-checklist"] },
      { title: "Prepare handover package", aiAssistance: ["generate-document", "create-report"] },
      { title: "Defect liability and close-out", aiAssistance: ["review-step"] },
    ],
    requiredDocuments: ["As-built drawings", "O&M manuals", "Test certificates"],
    requiredStandards: ["Contract completion requirements"],
    requiredCalculations: ["Final quantities"],
    professionalTools: ["Handover checklist", "Completion certificate template"],
    outputs: ["Completion certificate", "Handover dossier", "Final report"],
    qualityChecks: ["Snag clearance", "Document completeness"],
    completionChecklist: ["Handover complete", "DLP commenced", "Final account initiated"],
  },
] ;

export const civilWorkflowTemplates: WorkflowTemplate[] = civilWorkflowInputs.map(
  (workflow) =>
    buildWorkflowTemplate({
      ...workflow,
      disciplineId: CIVIL,
      disciplineName: CIVIL_NAME,
    })
);
