import { buildWorkflowTemplate } from "./buildWorkflowTemplate";
import type { WorkflowTemplate } from "../types";

const COMP = "computer-engineering";
const COMP_NAME = "Computer Engineering";

export const computerWorkflowTemplates: WorkflowTemplate[] = [
  buildWorkflowTemplate({
    id: "sdlc-workflow",
    disciplineId: COMP,
    disciplineName: COMP_NAME,
    title: "Software Development Lifecycle",
    overview: "End-to-end SDLC from requirements to deployment.",
    objective: "Deliver production-ready software with documented lifecycle.",
    prerequisites: ["Business requirements", "Tech stack decision", "Team roles"],
    activityTitles: [
      { title: "Requirements gathering and analysis" },
      { title: "System design and architecture", aiAssistance: ["create-report", "generate-document"] },
      { title: "Implementation and unit testing" },
      { title: "Integration and system testing", aiAssistance: ["generate-checklist"] },
      { title: "Deployment and handover", aiAssistance: ["review-step", "create-report"] },
    ],
    requiredDocuments: ["SRS", "Design document", "Test plan"],
    requiredStandards: ["Coding standards", "Security guidelines"],
    requiredCalculations: ["Capacity planning", "Performance benchmarks"],
    professionalTools: ["Design doc template", "Test checklist"],
    outputs: ["SRS", "Design document", "Test report", "Release notes"],
    qualityChecks: ["Code review", "Security scan", "UAT sign-off"],
    completionChecklist: ["Deployed", "Documentation complete", "Handover done"],
  }),
  buildWorkflowTemplate({
    id: "api-development-workflow",
    disciplineId: COMP,
    disciplineName: COMP_NAME,
    title: "API Development",
    overview: "REST/GraphQL API design, development, and documentation.",
    objective: "Deliver documented, tested APIs.",
    prerequisites: ["API requirements", "Auth strategy", "Data model"],
    activityTitles: [
      { title: "Define API contract and endpoints" },
      { title: "Design data models and auth", aiAssistance: ["generate-document"] },
      { title: "Implement and unit test APIs" },
      { title: "Generate API documentation", aiAssistance: ["generate-document", "create-report"] },
      { title: "API review and release", aiAssistance: ["review-step"] },
    ],
    requiredDocuments: ["API spec", "OpenAPI draft"],
    requiredStandards: ["REST conventions", "OpenAPI", "OAuth/OIDC"],
    requiredCalculations: ["Rate limits", "Latency targets"],
    professionalTools: ["API doc generator", "Postman collection"],
    outputs: ["API documentation", "OpenAPI spec", "Test collection"],
    qualityChecks: ["Contract tests", "Security review"],
    completionChecklist: ["API published", "Docs live"],
  }),
  buildWorkflowTemplate({
    id: "database-design-workflow",
    disciplineId: COMP,
    disciplineName: COMP_NAME,
    title: "Database Design",
    overview: "Database schema design, normalization, and optimization.",
    objective: "Produce optimized database design with documentation.",
    prerequisites: ["Data requirements", "Access patterns", "Volume estimates"],
    activityTitles: [
      { title: "Analyze data requirements" },
      { title: "Design ER model and schema", aiAssistance: ["create-report", "generate-document"] },
      { title: "Define indexes and constraints" },
      { title: "Review performance and security", aiAssistance: ["review-step"] },
      { title: "Publish schema documentation", aiAssistance: ["generate-document"] },
    ],
    requiredDocuments: ["Data dictionary", "ER diagram"],
    requiredStandards: ["Naming conventions", "SQL standards"],
    requiredCalculations: ["Storage estimates", "Query performance"],
    professionalTools: ["ER tool", "Schema doc template"],
    outputs: ["ER diagram", "DDL scripts", "Data dictionary"],
    qualityChecks: ["Normalization", "Index review"],
    completionChecklist: ["Schema approved", "Migrations ready"],
  }),
  buildWorkflowTemplate({
    id: "ai-model-development-workflow",
    disciplineId: COMP,
    disciplineName: COMP_NAME,
    title: "AI Model Development",
    overview: "ML/AI model development from data to deployment.",
    objective: "Deliver trained, validated, and documented AI model.",
    prerequisites: ["Problem definition", "Dataset", "Success metrics"],
    activityTitles: [
      { title: "Define problem and success metrics" },
      { title: "Prepare and explore dataset" },
      { title: "Train and evaluate models", aiAssistance: ["create-report"] },
      { title: "Validate and document model", aiAssistance: ["generate-document", "review-step"] },
      { title: "Deploy and monitor", aiAssistance: ["generate-checklist"] },
    ],
    requiredDocuments: ["Model card", "Dataset documentation"],
    requiredStandards: ["ML best practices", "Ethics guidelines"],
    requiredCalculations: ["Accuracy metrics", "Bias analysis"],
    professionalTools: ["Experiment tracker", "Model card template"],
    outputs: ["Model card", "Evaluation report", "Deployment guide"],
    qualityChecks: ["Validation set performance", "Bias review"],
    completionChecklist: ["Model deployed", "Monitoring active"],
  }),
];
