import { buildWorkflowTemplate } from "./buildWorkflowTemplate";
import type { WorkflowTemplate } from "../types";

const ELEC = "electrical-engineering";
const ELEC_NAME = "Electrical Engineering";

export const electricalWorkflowTemplates: WorkflowTemplate[] = [
  buildWorkflowTemplate({
    id: "load-calculation-workflow",
    disciplineId: ELEC,
    disciplineName: ELEC_NAME,
    title: "Load Calculation Workflow",
    overview: "Electrical load assessment and demand calculation.",
    objective: "Determine connected load, demand factor, and design load.",
    prerequisites: ["Equipment list", "Single line diagram draft", "Diversity factors"],
    activityTitles: [
      { title: "Compile connected load schedule" },
      { title: "Apply diversity and demand factors", aiAssistance: ["create-report"] },
      { title: "Calculate design load and MD", aiAssistance: ["suggest-standard"] },
      { title: "Prepare load calculation report", aiAssistance: ["generate-document"] },
      { title: "Review and approve", aiAssistance: ["review-step"] },
    ],
    requiredDocuments: ["Equipment schedule", "SLD draft"],
    requiredStandards: ["IS:3043", "IE Rules", "NBC"],
    requiredCalculations: ["Connected load", "Demand load", "MD"],
    professionalTools: ["Load calculator", "Load schedule template"],
    outputs: ["Load calculation sheet", "Load schedule"],
    qualityChecks: ["Diversity factors verified", "Future load allowance"],
    completionChecklist: ["Calculations approved", "Schedule issued"],
  }),
  buildWorkflowTemplate({
    id: "transformer-selection-workflow",
    disciplineId: ELEC,
    disciplineName: ELEC_NAME,
    title: "Transformer Selection Workflow",
    overview: "Transformer sizing and selection for power distribution.",
    objective: "Select appropriate transformer rating and configuration.",
    prerequisites: ["Load calculation", "Voltage levels", "Ambient conditions"],
    activityTitles: [
      { title: "Review load and voltage requirements" },
      { title: "Calculate transformer kVA rating", aiAssistance: ["create-report"] },
      { title: "Select transformer type and cooling", aiAssistance: ["suggest-standard"] },
      { title: "Prepare transformer specification", aiAssistance: ["generate-document"] },
      { title: "Technical review", aiAssistance: ["review-step"] },
    ],
    requiredDocuments: ["Load report", "Site conditions"],
    requiredStandards: ["IS:2026", "IS:1180", "IEC 60076"],
    requiredCalculations: ["kVA sizing", "Impedance", "Losses"],
    professionalTools: ["Transformer calculator", "Spec template"],
    outputs: ["Transformer datasheet", "Selection report"],
    qualityChecks: ["Rating margin", "Cooling adequacy"],
    completionChecklist: ["Transformer selected", "Spec approved"],
  }),
  buildWorkflowTemplate({
    id: "cable-design-workflow",
    disciplineId: ELEC,
    disciplineName: ELEC_NAME,
    title: "Cable Design Workflow",
    overview: "Cable sizing, routing, and schedule preparation.",
    objective: "Design cable system with correct sizing and protection.",
    prerequisites: ["Load data", "Route lengths", "Installation method"],
    activityTitles: [
      { title: "Define cable routes and lengths" },
      { title: "Calculate cable current capacity", aiAssistance: ["create-report"] },
      { title: "Select cable size and type", aiAssistance: ["suggest-standard"] },
      { title: "Prepare cable schedule", aiAssistance: ["generate-document", "prepare-boq"] },
      { title: "Design review", aiAssistance: ["review-step"] },
    ],
    requiredDocuments: ["SLD", "Layout drawings"],
    requiredStandards: ["IS:1554", "IS:7098", "IE Rules"],
    requiredCalculations: ["Current capacity", "Voltage drop", "Short circuit"],
    professionalTools: ["Cable calculator", "Cable schedule template"],
    outputs: ["Cable schedule", "Sizing calculations"],
    qualityChecks: ["VD within limits", "Derating applied"],
    completionChecklist: ["Schedule complete", "Protection coordinated"],
  }),
  buildWorkflowTemplate({
    id: "testing-commissioning-workflow",
    disciplineId: ELEC,
    disciplineName: ELEC_NAME,
    title: "Testing & Commissioning Workflow",
    overview: "Electrical testing and commissioning procedures.",
    objective: "Complete T&C with documented test results.",
    prerequisites: ["Installation complete", "Test equipment calibrated", "T&C plan"],
    activityTitles: [
      { title: "Review T&C plan", aiAssistance: ["suggest-standard"] },
      { title: "Conduct pre-commissioning checks", aiAssistance: ["generate-checklist"] },
      { title: "Perform electrical tests", aiAssistance: ["generate-inspection"] },
      { title: "Record results and prepare report", aiAssistance: ["create-report"] },
      { title: "Commissioning sign-off", aiAssistance: ["review-step"] },
    ],
    requiredDocuments: ["T&C plan", "Test procedures"],
    requiredStandards: ["IS:3043", "IEC test standards"],
    requiredCalculations: ["IR values", "Polarity", "Ratio tests"],
    professionalTools: ["Testing checklist", "Commissioning report"],
    outputs: ["Test reports", "Commissioning certificate"],
    qualityChecks: ["Calibration valid", "Results within limits"],
    completionChecklist: ["All tests passed", "Certificate issued"],
  }),
];
