import { buildWorkflowTemplate } from "./buildWorkflowTemplate";
import type { WorkflowTemplate } from "../types";

const MECH = "mechanical-engineering";
const MECH_NAME = "Mechanical Engineering";

export const mechanicalWorkflowTemplates: WorkflowTemplate[] = [
  buildWorkflowTemplate({
    id: "machine-design-workflow",
    disciplineId: MECH,
    disciplineName: MECH_NAME,
    title: "Machine Design Workflow",
    overview: "Machine element and assembly design from requirements to drawings.",
    objective: "Deliver validated machine design with calculations and specifications.",
    prerequisites: ["Design requirements", "Load conditions", "Material properties"],
    activityTitles: [
      { title: "Define design requirements and constraints" },
      { title: "Select materials and standards", aiAssistance: ["suggest-standard"] },
      { title: "Perform design calculations", aiAssistance: ["create-report"] },
      { title: "Create assembly and part specifications" },
      { title: "Design review and release", aiAssistance: ["review-step", "generate-checklist"] },
    ],
    requiredDocuments: ["Design brief", "Load diagram"],
    requiredStandards: ["IS/ASME standards", "Material specs"],
    requiredCalculations: ["Stress analysis", "Fatigue", "Factor of safety"],
    professionalTools: ["Design calculator", "CAD checklist"],
    outputs: ["Design report", "Part specifications", "Drawing list"],
    qualityChecks: ["FOS verified", "Tolerance review"],
    completionChecklist: ["Calculations approved", "Drawings released"],
  }),
  buildWorkflowTemplate({
    id: "manufacturing-workflow",
    disciplineId: MECH,
    disciplineName: MECH_NAME,
    title: "Manufacturing Workflow",
    overview: "Manufacturing process planning and production documentation.",
    objective: "Define manufacturing route, tooling, and quality plan.",
    prerequisites: ["Approved drawings", "Production volume", "Material availability"],
    activityTitles: [
      { title: "Review drawings and tolerances" },
      { title: "Define process route and tooling" },
      { title: "Prepare work instructions", aiAssistance: ["generate-document"] },
      { title: "Set up quality control plan", aiAssistance: ["generate-checklist"] },
      { title: "Production release", aiAssistance: ["review-step"] },
    ],
    requiredDocuments: ["Drawings", "BOM", "Process plan template"],
    requiredStandards: ["ISO 9001", "Company QMS"],
    requiredCalculations: ["Cycle time", "Capacity"],
    professionalTools: ["Process plan template", "FMEA sheet"],
    outputs: ["Process plan", "Work instructions", "QC plan"],
    qualityChecks: ["First article inspection", "Process capability"],
    completionChecklist: ["Process approved", "QC plan active"],
  }),
  buildWorkflowTemplate({
    id: "maintenance-workflow",
    disciplineId: MECH,
    disciplineName: MECH_NAME,
    title: "Maintenance Workflow",
    overview: "Preventive and corrective maintenance planning.",
    objective: "Establish maintenance schedule and procedures.",
    prerequisites: ["Equipment list", "OEM manuals", "Failure history"],
    activityTitles: [
      { title: "Classify equipment criticality" },
      { title: "Define maintenance strategy", aiAssistance: ["suggest-standard"] },
      { title: "Prepare maintenance schedule", aiAssistance: ["generate-checklist"] },
      { title: "Create lubrication and spare parts plan" },
      { title: "Maintenance program review", aiAssistance: ["review-step"] },
    ],
    requiredDocuments: ["Equipment register", "OEM manuals"],
    requiredStandards: ["Maintenance standards", "Safety procedures"],
    requiredCalculations: ["MTBF/MTTR analysis"],
    professionalTools: ["Maintenance checklist", "Lubrication schedule"],
    outputs: ["PM schedule", "Lubrication chart", "Spare parts list"],
    qualityChecks: ["Schedule coverage", "Safety review"],
    completionChecklist: ["Schedule published", "Spares identified"],
  }),
  buildWorkflowTemplate({
    id: "inspection-workflow",
    disciplineId: MECH,
    disciplineName: MECH_NAME,
    title: "Inspection Workflow",
    overview: "Machine and equipment inspection procedures.",
    objective: "Conduct systematic inspection with documented findings.",
    prerequisites: ["Inspection plan", "Equipment access", "Calibration records"],
    activityTitles: [
      { title: "Plan inspection scope" },
      { title: "Conduct visual and dimensional checks", aiAssistance: ["generate-inspection"] },
      { title: "Record findings and measurements" },
      { title: "Prepare inspection report", aiAssistance: ["create-report"] },
      { title: "Follow-up actions", aiAssistance: ["review-step"] },
    ],
    requiredDocuments: ["Inspection plan", "Previous reports"],
    requiredStandards: ["Inspection standards"],
    requiredCalculations: ["Wear analysis"],
    professionalTools: ["Inspection format", "Machine inspection report"],
    outputs: ["Inspection report", "Action list"],
    qualityChecks: ["Calibration valid", "Findings documented"],
    completionChecklist: ["Report issued", "Actions assigned"],
  }),
  buildWorkflowTemplate({
    id: "production-workflow",
    disciplineId: MECH,
    disciplineName: MECH_NAME,
    title: "Production Workflow",
    overview: "Production planning, execution, and monitoring.",
    objective: "Optimize production output with quality and safety compliance.",
    prerequisites: ["Production plan", "Raw material availability", "Workforce"],
    activityTitles: [
      { title: "Plan production batch" },
      { title: "Set up line and tooling" },
      { title: "Execute production run", aiAssistance: ["generate-checklist"] },
      { title: "Monitor KPIs and quality", aiAssistance: ["create-report"] },
      { title: "Production close-out", aiAssistance: ["review-step"] },
    ],
    requiredDocuments: ["Production order", "SOPs"],
    requiredStandards: ["Quality standards", "Safety standards"],
    requiredCalculations: ["OEE", "Yield"],
    professionalTools: ["Production log", "QC checklist"],
    outputs: ["Production report", "QC records"],
    qualityChecks: ["In-process checks", "Final inspection"],
    completionChecklist: ["Batch complete", "Records filed"],
  }),
];
