import type { EngineeringQueryIntent } from "../ai/reasoningEngine/types";
import type { CopilotSuggestion } from "../copilot/types";
import type { EngineeringDeliverableType } from "../actions/types";
import type { WorkspaceCategoryId } from "../workspace/utils/workspaceCategoryConfig";

export interface ChatMessageMetadata {
  followUpIntent?: string | null;
  queryIntent?: EngineeringQueryIntent;
  providerId?: string;
  disciplineId?: string | null;
  disciplineName?: string | null;
  moduleId?: WorkspaceCategoryId | null;
  sessionTopic?: string | null;
  suggestedDeliverables?: EngineeringDeliverableType[];
  copilotSuggestions?: CopilotSuggestion[];
  copilotIntent?: string | null;
  suggestedModuleId?: string | null;
  projectId?: string | null;
  projectName?: string | null;
  activeAgentId?: string | null;
  activeAgentName?: string | null;
  decisionSupportActive?: boolean;
  decisionCategory?: string | null;
  decisionComparisonTitle?: string | null;
  decisionConfidenceLevel?: string | null;
  orchestratorIntent?: string | null;
  orchestratorPrimaryModule?: string | null;
  orchestratorMultiModule?: boolean;
  knowledgeEntryCount?: number;
  knowledgeStandardsCount?: number;
  documentIntelligenceActive?: boolean;
  documentIntent?: string | null;
  documentCount?: number;
  complianceActive?: boolean;
  complianceReviewIntent?: string | null;
  complianceScore?: number | null;
  complianceConfidence?: string | null;
  auditActive?: boolean;
  auditType?: string | null;
  auditReviewMode?: string | null;
  auditObservationCount?: number;
  feedbackRecorded?: boolean;
  experienceLevel?: string | null;
  assistantActive?: boolean;
  pendingTaskCount?: number;
  assistantTaskAction?: string | null;
  marketplaceActive?: boolean;
  marketplaceListingCount?: number;
  marketplaceListingAction?: string | null;
  templatesActive?: boolean;
  templateCount?: number;
  documentGenerated?: boolean;
  templateAction?: string | null;
  workflowAutomationActive?: boolean;
  activeWorkflowTitle?: string | null;
  workflowCompletionPercent?: number | null;
  workflowAction?: string | null;
  designWizardActive?: boolean;
  activeDesignTitle?: string | null;
  designStepProgress?: string | null;
  designCompleteness?: number | null;
  designAction?: string | null;
  estimationActive?: boolean;
  activeEstimateTitle?: string | null;
  estimateItemCount?: number;
  estimateTotalCost?: number | null;
  estimationAction?: string | null;
  tenderActive?: boolean;
  activeTenderTitle?: string | null;
  tenderRiskCount?: number;
  tenderAction?: string | null;
  contractActive?: boolean;
  activeContractTitle?: string | null;
  contractRiskCount?: number;
  contractAction?: string | null;
  claimAction?: string | null;
  researchActive?: boolean;
  activeResearchTopic?: string | null;
  researchAction?: string | null;
  researchReportAction?: string | null;
  mentorActive?: boolean;
  activeMentorFocus?: string | null;
  mentorAction?: string | null;
  mentorReportAction?: string | null;
  knowledgeCaptureActive?: boolean;
  activeLessonsWorkspace?: string | null;
  lessonCount?: number;
  lessonAction?: string | null;
  lessonReportAction?: string | null;
  siteExecutionActive?: boolean;
  activeSiteWorkspace?: string | null;
  siteExecutionPhase?: string | null;
  siteExecutionAction?: string | null;
  siteReportAction?: string | null;
  dashboardActive?: boolean;
  dashboardAction?: string | null;
  dashboardSearchCount?: number;
}

export interface ChatMessage {
  id: string;
  role: "user" | "assistant";
  content: string;
  timestamp: Date;
  metadata?: ChatMessageMetadata;
}
