CREATE TABLE IF NOT EXISTS healthchecks (
  id SERIAL PRIMARY KEY,
  status TEXT NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

INSERT INTO healthchecks (status) VALUES ('ok') ON CONFLICT DO NOTHING;
